server:
   port: 8003
   
# 定义当前服务名
spring:
   application:
      name: cruser
   datasource:
      url: jdbc:mysql://127.0.0.1/c83-s2-ply-damai
      username: root
      password: a
      driver-class-name: com.mysql.jdbc.Driver