server:
   port: 8003
   
# 定义当前服务名
spring:
   application:
      name: cruser
   datasource:
      url: jdbc:mysql://127.0.0.1/crbook
      username: root
      password: a
      driver-class-name: com.mysql.jdbc.Driver

#日志配置
logging:
   level:
      com:
         yc:
            crbook:
               dao: debug
               web: warn