#配置端口
server:
   port: 8088


 # 定义当前服务名
spring:
   application:
      name: zuul
      
# 配置Eureka 服务器的地址
eureka:
   client:
      serviceUrl:
         defaultZone: http://es1:8000/eureka,http://es2:7999/eureka 

# zuul 路由配置
# http://es3/user/user   ==>   http://es1:8001/user
# http://es3/order/order ==>   http://es1:8002/order

zuul:
   # 后面不定义配置参数, 表示 无敏感头 ==> 空集合
   #配置在zuul下，配置全局的敏感头设置
   sensitiveHeaders: 
   #忽略路由
   #默认忽略所有的服务，除了单独配置的路由
   #ignoredServices: '*'
   routes:
      #路由名(简单路由)
      simple:
         #映射地址
         path: /simple/163
         #简单路由url地址   使用http和https开头的地址
         url: http://www.163.com
         
      #路由名(跳转路由) 跳转到当前项目的某个action方法
      forward:
         #映射地址
         path: /forward/**
         #使用forward：开头
         url: forward:/test
         
      #路由名(Ribbon路由)
      user:
         # 对应接口的地址  /** 表示所有的接口(包含子目录)
         path: /user/**
         serviceId: user
         # 敏感头设置,  数据类型是集合
         # sensitiveHeaders: Authorization
         
      order:
         # 对应接口的地址  /** 表示所有的接口(包含子目录)
         path: /order/**
         serviceId: order
      
      #默认路由    上面没有映射到会映射到下面
      #http://127.0.0.1/  ==>https://music.163.com/
      lagacy:
         path: /**
         url: https://music.163.com/

hystrix:
   command:
      default:
         execution:
            isolation:
               thread:
                  #设置超时为1分钟
                  timeoutInMilliseconds: 60000 
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
